### ISSUE TITLE
error corriendo trabajo en nodos katsina

### ISSUE THREAD

**Issue by ldalcaraz** [sostenibilidad-unam/supercomputadora#1]
Ejecutando el script de prueba, existen errores de permisos, quizá para varios de los usuarios creados ayer. Aquí va la salida:

001 (054.000.000) 10/27 01:01:41 Job executing on host: <192.168.0.13:36206?addr
s=192.168.0.13-36206>
...
007 (054.000.000) 10/27 01:01:41 Shadow exception!
	Error from slot1@katsina3.lancis.ecologia.unam.mx: Failed to execute '/s
rv/home/lalcaraz/main.sh': (errno=13: 'Permission denied')
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
...
012 (054.000.000) 10/27 01:01:41 Job was held.
	Error from slot1@katsina3.lancis.ecologia.unam.mx: Failed to execute '/s
rv/home/lalcaraz/main.sh': (errno=13: 'Permission denied')
	Code 6 Subcode 13
...

**Comment by rgarcia-herrera** [comment]
main.sh no tenía permisos de ejecución. Lo resolví así:

    $ chmod +x main.sh

Lo corrí vía submit_file.condor.
