### ISSUE TITLE
dependencias en nodos katsina

### ISSUE THREAD

**Issue by ldalcaraz** [sostenibilidad-unam/supercomputadora#2]
para ejecutar qiime en nodos katsina, hace falta instalar las mismas dependencias que en el nodo maestro:

python-dev libncurses5-dev libssl-dev libzmq-dev libgsl0-dev openjdk-6-jdk libxml2 libxslt1.1 libxslt1-dev ant git subversion build-essential zlib1g-dev libpng12-dev libfreetype6-dev mpich2 libreadline-dev gfortran unzip libmysqlclient18 libmysqlclient-dev ghc sqlite3 libsqlite3-dev libc6-i386 libbz2-dev tcl-dev tk-dev r-base r-base-dev libatlas-dev libatlas-base-dev liblapack-dev swig libhdf5-serial-dev

​La información de estos paquetes esta aquí:

https://github.com/qiime/qiime-deploy

la salida cuando se prueba el script de configuración en los nodos katsina es:

print_qiime_config.py -t
Traceback (most recent call last):
  File "/srv/home/lalcaraz/qiime/1.9.1/bin/print_qiime_config.py", line 40, in <module>
    raise ImportError("%s\n%s" % (e, core_dependency_missing_msg))
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
See the QIIME Installation Guide: http://qiime.org/install/install.html

Cuando se prueba en el maestro es:

$ print_qiime_config.py -t

System information
==================
         Platform:	linux2
   Python version:	2.7.3 (default, Oct 26 2016, 18:10:53)  [GCC 4.9.2]
Python executable:	/srv/home/lalcaraz/qiime/1.9.1/bin/python

QIIME default reference information
===================================
For details on what files are used as QIIME's default references, see here:
 https://github.com/biocore/qiime-default-reference/releases/tag/0.1.3

Dependency versions
===================
          QIIME library version:	1.9.1
           QIIME script version:	1.9.1
qiime-default-reference version:	0.1.3
                  NumPy version:	1.11.2
                  SciPy version:	0.18.1
                 pandas version:	0.19.0
             matplotlib version:	1.5.3
            biom-format version:	2.1.5
                   h5py version:	Not installed.
                   qcli version:	0.1.1
                   pyqi version:	0.3.2
             scikit-bio version:	0.2.3
                 PyNAST version:	1.2.2
                Emperor version:	0.9.51
                burrito version:	0.9.1
       burrito-fillings version:	0.1.1
              sortmerna version:	SortMeRNA version 2.0, 29/11/2014
              sumaclust version:	SUMACLUST Version 1.0.00
                  swarm version:	Swarm 1.2.19 [Oct 26 2016 15:46:15]
                          gdata:	Installed.

QIIME config values
===================
For definitions of these settings and to learn how to configure QIIME, see here:
 http://qiime.org/install/qiime_config.html
 http://qiime.org/tutorials/parallel_qiime.html

                     blastmat_dir:	/srv/home/lalcaraz/qiime/qiime_software/blast-2.2.22-release/data
      pick_otus_reference_seqs_fp:	/srv/home/lalcaraz/qiime/1.9.1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                         sc_queue:	all.q
      topiaryexplorer_project_dir:	None
     pynast_template_alignment_fp:	/srv/home/lalcaraz/qiime/1.9.1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta
                  cluster_jobs_fp:	start_parallel_jobs.py
pynast_template_alignment_blastdb:	None
assign_taxonomy_reference_seqs_fp:	/srv/home/lalcaraz/qiime/1.9.1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
                     torque_queue:	friendlyq
                    jobs_to_start:	40
                       slurm_time:	None
            denoiser_min_per_core:	50
assign_taxonomy_id_to_taxonomy_fp:	/srv/home/lalcaraz/qiime/1.9.1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt
                         temp_dir:	/tmp/
                     slurm_memory:	None
                      slurm_queue:	None
                      blastall_fp:	/srv/home/lalcaraz/qiime/qiime_software/blast-2.2.22-release/bin/blastall
                 seconds_to_sleep:	1

QIIME base install test results
===============================
.........
----------------------------------------------------------------------
Ran 9 tests in 0.173s

OK

**Comment by rgarcia-herrera** [comment]
Acá muestro cómo instalarse qiime en un ambiente virtual y un ejemplo de cómo correrlo en los nodos de cómputo: ceff604d4c392cd4d9a565880a01694c6d608b92
